# Dockerfile-plugin will be based on this when multistage build
# is released for Docker Hub

# builder
FROM golang:1.8.3-alpine as builder
RUN apk add --no-cache git openssh-client build-base
RUN go get -d -v github.com/mholt/caddy
RUN sed -i '/This is where other plugins get plugged in (imported)/a _ "github.com/abiosoft/caddyplug"' \
  /go/src/github.com/mholt/caddy/caddy/caddymain/run.go
RUN go get -v github.com/mholt/caddy/caddy
RUN go get -v github.com/abiosoft/caddyplug/caddyplug

# image
FROM alpine:3.5
LABEL maintainer "Abiola Ibrahim <abiola89@gmail.com>"

LABEL caddy_version="0.10.4" architecture="amd64"

RUN apk add --no-cache openssh-client git tar curl

COPY --from=builder /go/bin/caddy /usr/bin/caddy
RUN chmod 0755 /usr/bin/caddy \
 && /usr/bin/caddy -version

EXPOSE 80 443 2015
VOLUME /root/.caddy
WORKDIR /srv

COPY Caddyfile /etc/Caddyfile
COPY index.html /srv/index.html

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout"]
