FROM golang:1.8.3-alpine
LABEL maintainer "Abiola Ibrahim <abiola89@gmail.com>"

LABEL caddy_version="0.10.4" architecture="amd64"

RUN apk add --no-cache git build-base

# install caddyplug
RUN go get -v github.com/abiosoft/caddyplug/caddyplug \
 && mv /go/bin/caddyplug /usr/bin/caddyplug \
 && /usr/bin/caddyplug list

# install caddy using caddyplug
RUN /usr/bin/caddyplug install-caddy

EXPOSE 80 443 2015
VOLUME /root/.caddy
WORKDIR /srv

COPY Caddyfile /etc/Caddyfile
COPY index.html /srv/index.html

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout"]
